# Подготовка данных для дашборда

Подготовка двух таблиц из `sales.xlsx` для дальнейшей работы в Yandex DataLens.

In [1]:
import pandas as pd

sales = pd.read_excel("data/raw/sales.xlsx", sheet_name="Product")
brands = pd.read_excel("data/raw/sales.xlsx", sheet_name="Dynamic")

## Знакомство с данными

In [2]:
sales.head()

        SKU                   Категория  ... Средний % выкупа (Ноябрь)    Страна
0  13856867               Уход за кожей  ...                      0.93    Россия
1  46825817               Уход за кожей  ...                      0.94    Россия
2  51524888  Профессиональная косметика  ...                      0.99    Россия
3  56236410     Средства личной гигиены  ...                      1.00    Россия
4  16898570                      Макияж  ...                      0.94  Беларусь

[5 rows x 13 columns]

In [3]:
brands.head()

          Бренд      Месяц  Продажи    Выручка  Средний % выкупа
0  188cosmetics 2023-12-01     5844  2315498.0             0.960
1  188cosmetics 2023-11-01     4423  1890118.2             0.964
2  188cosmetics 2023-10-01     3093  1225502.0             0.901
3  188cosmetics 2023-09-01     3399  1346745.0             0.920
4  188cosmetics 2023-08-01     3685  1460063.0             0.884

In [4]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91332 entries, 0 to 91331
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SKU                         91332 non-null  int64
 1   Категория                   91332 non-null  object
 2   Предмет                     91332 non-null  object
 3   Бренд                       91332 non-null  object
 4   Цена (Декабрь)              91332 non-null  int64
 5   Цена (Ноябрь)               91332 non-null  float64
 6   Продажи (Декабрь)           91332 non-null  int64
 7   Продажи (Ноябрь)            91332 non-null  int64
 8   Выручка (Декабрь)           91332 non-null  int64
 9   Выручка (Ноябрь)            91332 non-null  float64
 10  Средний % выкупа (Декабрь)  91332 non-null  float64
 11  Средний % выкупа (Ноябрь)   91332 non-null  float64
 12  Страна                      91332 non-null  object
dtypes: float64(4), int64(5), object(4)
memory usage: 9.1+ MB

In [5]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Бренд             6000 non-null   object
 1   Месяц             6000 non-null   datetime64[ns]
 2   Продажи           6000 non-null   int64
 3   Выручка           6000 non-null   float64
 4   Средний % выкупа  6000 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 234.5+ KB

In [6]:
brands["Месяц"].sort_values().unique()

<DatetimeArray>
['2023-07-01 00:00:00', '2023-08-01 00:00:00', '2023-09-01 00:00:00',
 '2023-10-01 00:00:00', '2023-11-01 00:00:00', '2023-12-01 00:00:00']
Length: 6, dtype: datetime64[ns]

In [7]:
sales.columns

Index(['SKU', 'Категория', 'Предмет', 'Бренд', 'Цена (Декабрь)',
       'Цена (Ноябрь)', 'Продажи (Декабрь)', 'Продажи (Ноябрь)',
       'Выручка (Декабрь)', 'Выручка (Ноябрь)', 'Средний % выкупа (Декабрь)',
       'Средний % выкупа (Ноябрь)', 'Страна'],
      dtype='object')

In [8]:
sales.isna().sum()

SKU                           0
Категория                     0
Предмет                       0
Бренд                         0
Цена (Декабрь)                0
Цена (Ноябрь)                 0
Продажи (Декабрь)             0
Продажи (Ноябрь)              0
Выручка (Декабрь)             0
Выручка (Ноябрь)              0
Средний % выкупа (Декабрь)    0
Средний % выкупа (Ноябрь)     0
Страна                        0
dtype: int64

In [9]:
brands.isna().sum()

Бренд               0
Месяц               0
Продажи             0
Выручка             0
Средний % выкупа    0
dtype: int64

In [10]:
sales.duplicated().sum()

np.int64(0)

In [11]:
brands.duplicated().sum()

np.int64(0)

## Переименование столбцов

In [12]:
main_columns = {
    "SKU": "sku",
    "Категория": "category",
    "Предмет": "product_type",
    "Бренд": "brand",
    "Страна": "country"
}

metrics = {
    "Цена": "price",
    "Продажи": "sales_sum",
    "Выручка": "revenue_sum",
    "Средний % выкупа": "avg_buyout"
}

months = {
    "Ноябрь": "november",
    "Декабрь": "december"
}


def rename_column(column):
    if column in main_columns:
        return main_columns[column]

    if "(" in column and ")" in column:
        metric, month = column.split("(")
        metric = metrics.get(metric.strip())
        month = months.get(month.strip(") "))

        if metric and month:
            return f"{metric}_{month}"

    return column

In [13]:
sales = sales.rename(columns=rename_column)
sales.head()

        sku                    category  ... avg_buyout_november   country
0  13856867               Уход за кожей  ...                0.93    Россия
1  46825817               Уход за кожей  ...                0.94    Россия
2  51524888  Профессиональная косметика  ...                0.99    Россия
3  56236410     Средства личной гигиены  ...                1.00    Россия
4  16898570                      Макияж  ...                0.94  Беларусь

[5 rows x 13 columns]

In [14]:
brands = brands.rename(columns={
    "Бренд": "brand",
    "Месяц": "month",
    "Продажи": "sales_sum",
    "Выручка": "revenue_sum",
    "Средний % выкупа": "avg_buyout"
})

brands.head()

          brand      month  sales_sum  revenue_sum  avg_buyout
0  188cosmetics 2023-12-01       5844    2315498.0       0.960
1  188cosmetics 2023-11-01       4423    1890118.2       0.964
2  188cosmetics 2023-10-01       3093    1225502.0       0.901
3  188cosmetics 2023-09-01       3399    1346745.0       0.920
4  188cosmetics 2023-08-01       3685    1460063.0       0.884

## Преобразование таблицы Product

Перевожу показатели ноября и декабря из отдельных столбцов в длинный формат.

In [15]:
id_columns = [
    "sku",
    "category",
    "product_type",
    "brand",
    "country"
]

sales_long = sales.melt(
    id_vars=id_columns,
    var_name="metric_month",
    value_name="value"
)

sales_long[["metric", "month_name"]] = (
    sales_long["metric_month"]
    .str.rsplit("_", n=1, expand=True)
)

sales_long = (
    sales_long
    .pivot_table(
        index=id_columns + ["month_name"],
        columns="metric",
        values="value",
        aggfunc="first"
    )
    .reset_index()
)

sales_long.columns.name = None

sales_long = sales_long.rename(columns={
    "sales_sum": "sales",
    "revenue_sum": "revenue"
})

month_numbers = {
    "november": 11,
    "december": 12
}

sales_long["month"] = pd.to_datetime({
    "year": 2023,
    "month": sales_long["month_name"].map(month_numbers),
    "day": 1
})

sales = sales_long.drop(columns="month_name")

In [16]:
sales.head()

      sku    category    product_type  ...    revenue  sales      month
0  302299      Макияж            Туши  ...  144744.00  207.0 2023-12-01
1  302299      Макияж            Туши  ...  155110.86  229.0 2023-11-01
2  353931  Парфюмерия  Туалетная вода  ...  276360.00  185.0 2023-12-01
3  353931  Парфюмерия  Туалетная вода  ...  280501.48  196.0 2023-11-01
4  353932  Парфюмерия  Туалетная вода  ...  300936.00  210.0 2023-12-01

[5 rows x 10 columns]

In [17]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182664 entries, 0 to 182663
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   sku           182664 non-null  int64
 1   category      182664 non-null  object
 2   product_type  182664 non-null  object
 3   brand         182664 non-null  object
 4   country       182664 non-null  object
 5   avg_buyout    182664 non-null  float64
 6   price         182664 non-null  float64
 7   revenue       182664 non-null  float64
 8   sales         182664 non-null  float64
 9   month         182664 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 13.9+ MB

In [18]:
sales.duplicated(["sku", "month"]).sum()

np.int64(0)

## Сохранение данных

In [19]:
sales.to_csv("data/processed/sales_clear.csv", index=False)
brands.to_csv("data/processed/brands_clear.csv", index=False)

В результате получены две таблицы для загрузки в DataLens:
данные по SKU и помесячная динамика по брендам.